apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  push:
    branches:
      - "**"
  workflow_dispatch:
jobs:
  build:
    steps:
      - uses: docker://golang:1.20.3-alpine3.17
        name: Say hello
        shell: sh
        run: |
          echo "hello world"
      - name: checkout-source-code
        uses: cloudbees-io/checkout@v1
      - name: Run gosec (SO)
        uses: cloudbees-io/gosec-sast-scan-code@v1
        kind: scan
      - name: Run sonarqube bundled action from platform
        uses: cloudbees-io/sonarqube-bundled-sast-scan-code@v1
        with:
          language: LANGUAGE_GO
